version: "3"
services:
  bitcoind:
    image: coblox/bitcoin-core:0.17.0
    command: -regtest
      -server
      -printtoconsole
      -bind=0.0.0.0:18444
      -rpcbind=0.0.0.0:18443
      -rpcauth=bitcoin:cb77f0957de88ff388cf817ddbc7273$$9eaa166ace0d94a29c6eceb831a42458e93faeb79f895a7ee4ce03f4343f8f55
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://*:28332
      -zmqpubrawtx=tcp://*:28333
      -acceptnonstdtxn=0
      -txindex
    ports:
      - "18443:18443"
      - "18444:18444"
      - "28332:28332"
      - "28333:28333"
